"""new field in user model

Revision ID: 227d601c2616
Revises: d9a1adb7f413
Create Date: 2018-11-07 22:36:48.329085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227d601c2616'
down_revision = 'd9a1adb7f413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
